.TH SQ-KEY-ADOPT "1" "JANUARY 2021" "0.24.0 (SEQUOIA-OPENPGP 1.0.0)" "USER COMMANDS" 5
.SH NAME
sq\-key\-adopt \- 
Binds keys from one certificate to another

This command allows one to transfer primary keys and subkeys into an
existing certificate.  Say you want to transition to a new
certificate, but have an authentication subkey on your current
certificate.  You want to keep the authentication subkey because it
allows access to SSH servers and updating their configuration is not
feasible.

.SH SYNOPSIS
\fBsq key adopt\fR [FLAGS] [OPTIONS] [TARGET\-KEY]
.SH FLAGS
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information

.TP
\fB\-\-allow\-broken\-crypto\fR
Allows adopting keys from certificates using broken cryptography

.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-keyring\fR KEY\-RING
Supplies keys for use in \-\-key.

.TP
\fB\-k\fR, \fB\-\-key\fR KEY
Adds the key or subkey KEY to the TARGET\-KEY

.TP
\fB\-o\fR, \fB\-\-output\fR FILE
Writes to FILE or stdout if omitted
.SH ARGS
.TP
TARGET\-KEY
Adds keys to TARGET\-KEY
.SH EXAMPLES
.TP
# Adopt an subkey into the new cert
\fB $ sq key adopt \-\-keyring juliet\-old.pgp \-\-key 0123456789ABCDEF \-\- juliet\-new.pgp\fR

.SH SEE ALSO
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.

.ad l
.nh
sq(1), sq\-armor(1), sq\-autocrypt(1), sq\-certify(1), sq\-dearmor(1), sq\-decrypt(1), sq\-encrypt(1), sq\-inspect(1), sq\-key(1), sq\-key\-adopt(1), sq\-key\-attest\-certifications(1), sq\-key\-extract\-cert(1), sq\-key\-generate(1), sq\-keyring(1), sq\-keyring\-filter(1), sq\-keyring\-join(1), sq\-keyring\-list(1), sq\-keyring\-merge(1), sq\-keyring\-split(1), sq\-keyserver(1), sq\-keyserver\-get(1), sq\-keyserver\-send(1), sq\-packet(1), sq\-sign(1), sq\-verify(1), sq\-wkd(1)


.SH AUTHORS
.P
.RS 2
.nf
Azul <azul@sequoia\-pgp.org>
Igor Matuszewski <igor@sequoia\-pgp.org>
Justus Winter <justus@sequoia\-pgp.org>
Kai Michaelis <kai@sequoia\-pgp.org>
Neal H. Walfield <neal@sequoia\-pgp.org>
Nora Widdecke <nora@sequoia\-pgp.org>
Wiktor Kwapisiewicz <wiktor@sequoia\-pgp.org>
