.TH SQ-KEYRING-JOIN "1" "MARCH 2021" "0.24.0 (SEQUOIA-OPENPGP 1.0.0)" "USER COMMANDS" 5
.SH NAME
sq\-keyring\-join \- Joins keys or keyrings into a single keyring

Unlike "sq keyring merge", multiple versions of the same key are not
merged together.

The converse operation is "sq keyring split".

.SH SYNOPSIS
\fBsq keyring join\fR [FLAGS] [OPTIONS] [\-\-] [FILE]
.SH FLAGS
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information

.TP
\fB\-B\fR, \fB\-\-binary\fR
Don't ASCII\-armor the keyring
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR FILE
Sets the output file to use
.SH ARGS
.TP
FILE
Sets the input files to use
.SH EXAMPLES
.TP
# Collect certs for an email conversation
\fB$ sq keyring join juliet.pgp romeo.pgp alice.pgp\fR

.SH SEE ALSO
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.

.ad l
.nh
sq(1), sq\-armor(1), sq\-certify(1), sq\-dearmor(1), sq\-decrypt(1), sq\-encrypt(1), sq\-inspect(1), sq\-key(1), sq\-key\-adopt(1), sq\-key\-attest\-certifications(1), sq\-key\-extract\-cert(1), sq\-key\-generate(1), sq\-keyring(1), sq\-keyring\-filter(1), sq\-keyring\-join(1), sq\-keyring\-list(1), sq\-keyring\-merge(1), sq\-keyring\-split(1), sq\-packet(1), sq\-sign(1), sq\-verify(1)


.SH AUTHORS
.P
.RS 2
.nf
Azul <azul@sequoia\-pgp.org>
Igor Matuszewski <igor@sequoia\-pgp.org>
Justus Winter <justus@sequoia\-pgp.org>
Kai Michaelis <kai@sequoia\-pgp.org>
Neal H. Walfield <neal@sequoia\-pgp.org>
Nora Widdecke <nora@sequoia\-pgp.org>
Wiktor Kwapisiewicz <wiktor@sequoia\-pgp.org>
