.TH SQ-VERIFY "1" "JANUARY 2021" " " "USER COMMANDS" 5
.SH NAME
sq verify \- Verifies signed messages or detached signatures

When verifying signed messages, the message is written to stdout or
the file given to \-\-output.

When a detached message is verified, no output is produced.  Detached
signatures are often used to sign software packages.

The converse operation is 'sq sign'.

.SH SYNOPSIS
\fBsq verify\fR [FLAGS] [OPTIONS] [\-\-] [FILE]
.SH FLAGS
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR FILE
Writes to FILE or stdout if omitted

.TP
\fB\-\-detached\fR SIG
Verifies a detached signature

.TP
\fB\-n\fR, \fB\-\-signatures\fR N
Sets the threshold of valid signatures to N. If this threshold is not reached, the message will not be considered verified.  [default: 0]

.TP
\fB\-\-signer\-cert\fR CERT
Verifies signatures with CERT
.SH ARGS
.TP
FILE
Reads from FILE or stdin if omitted
.SH EXAMPLES
.TP
Verify a signed message
\fB$ sq verify \-\-signer\-key juliet.pgp signed\-message.pgp\fR
.TP
Verify a detached message
\fB$ sq verify \-\-signer\-key juliet.pgp \-\-detached message.sig message.txt\fR

.SH SEE ALSO
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.

If you are looking for a standalone program to verify detached
signatures, consider using sequoia\-sqv.\fR

.ad l
.nh
sq(1), sq\-armor(1), sq\-autocrypt(1), sq\-certify(1), sq\-dearmor(1), sq\-decrypt(1), sq\-encrypt(1), sq\-inspect(1), sq\-key(1), sq\-keyring(1), sq\-packet(1), sq\-sign(1), sq\-verify(1), sqv(1)


.SH AUTHORS
.P
.RS 2
.nf
Azul <azul@sequoia\-pgp.org>
Igor Matuszewski <igor@sequoia\-pgp.org>
Justus Winter <justus@sequoia\-pgp.org>
Kai Michaelis <kai@sequoia\-pgp.org>
Neal H. Walfield <neal@sequoia\-pgp.org>
Nora Widdecke <nora@sequoia\-pgp.org>
Wiktor Kwapisiewicz <wiktor@sequoia\-pgp.org>
